let jokes = [
    "Why don't programmers like nature? It has too many bugs.",
    "I would tell you a UDP joke, but you might not get it.",
    "What is a computer's favorite snack? Microchips!",
    "Why did the programmer quit his job? He didn't get arrays.",
    "Why do programmers prefer dark mode? Less light means less bugs.",
    "99 little bugs in the code, 99 bugs in the code, fix one bug, compile again, 101 little bugs in the code.",
    "Why did the developer go broke? Because he used up all his cache.",
    "['hip', 'hip'] (hip hip array!)",
    "Why did the programmer get stuck in the shower? Because the instructions said: Lather, Rinse, Repeat.",
    "Why don't programmers like nature? It has too many bugs.",
    "What's a computer's favorite beat? An algo-rhythm.",
    "An SQL query walks into a bar, walks up to two tables, and asks: 'Can I join you?'",
    "Why do programmers prefer dark mode? Light attracts bugs.",
    "['ship'] (hip hip array!)",
    "What's the object-oriented way to become wealthy? Inheritance.",
    "What did the computer do at lunchtime? Had a byte!",
    "Why did the developer go broke? Because he used up all his cache.",
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "What's a computer's least favorite food? Spam.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 equals Dec 25.",
    "Why don't programmers like to go outside? The sun makes their screen go blank.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 equals Dec 25.",
    "['to err', 'to err'] is human. ['to arr'] is pirate!",
    "Why don't programmers like nature? It has too many bugs.",
    "Two bytes meet. The first byte asks, 'Are you ill?' The second byte replies, 'No, just feeling a bit off.'",
    "What's a computer's least favorite food? Spam.",
    "Why did the developer go broke? Because he used up all his cache.",
    "Why don't programmers like nature? It has too many bugs.",
    "What's a computer's favorite snack? Microchips!",
    "What is a computer's favorite beat? An algo-rhythm.",
    "Why did the programmer quit his job? He didn't get arrays.",
    "Why do programmers prefer dark mode? Less light means less bugs.",
    "99 little bugs in the code, 99 bugs in the code, fix one bug, compile again, 101 little bugs in the code.",
    "Why did the developer go broke? Because he used up all his cache.",
    "['hip', 'hip'] (hip hip array!)",
    "Why did the programmer get stuck in the shower? Because the instructions said: Lather, Rinse, Repeat.",
    "Why don't programmers like nature? It has too many bugs.",
    "What's a computer's favorite beat? An algo-rhythm.",
    "An SQL query walks into a bar, walks up to two tables, and asks: 'Can I join you?'",
    "Why do programmers prefer dark mode? Light attracts bugs.",
    "['ship'] (hip hip array!)",
    "What's the object-oriented way to become wealthy? Inheritance.",
    "What did the computer do at lunchtime? Had a byte!",
    "Why did the developer go broke? Because he used up all his cache.",
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "What's a computer's least favorite food? Spam.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 equals Dec 25.",
    "Why don't programmers like to go outside? The sun makes their screen go blank.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 equals Dec 25.",
    "['to err', 'to err'] is human. ['to arr'] is pirate!",
    "Why don't programmers like nature? It has too many bugs.",
    "Two bytes meet. The first byte asks, 'Are you ill?' The second byte replies, 'No, just feeling a bit off.'",
    "What's a computer's least favorite food? Spam.",
    "Why did the developer go broke? Because he used up all his cache.",
    "Why don't programmers like nature? It has too many bugs.",
    "['to err', 'to err'] is human. ['to arr'] is pirate!",
    "Why don't programmers like nature? It has too many bugs.",
    "What's a computer's least favorite food? Spam.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 equals Dec 25.",
    "Why don't programmers like to go outside? The sun makes their screen go blank.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 equals Dec 25.",
    "Why don't programmers like nature? It has too many bugs.",
    "Two bytes meet. The first byte asks, 'Are you ill?' The second byte replies, 'No, just feeling a bit off.'",
    "What's a computer's least favorite food? Spam.",
    "Why did the developer go broke? Because he used up all his cache.",
    "Why don't programmers like nature? It has too many bugs.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 equals Dec 25.",
    "Why don't programmers like to go outside? The sun makes their screen go blank.",
    "Why do programmers always mix up Christmas and Halloween? Because Oct 31 equals Dec 25.",
    "['to err', 'to err'] is human. ['to arr'] is pirate!",
    "Why don't programmers like nature? It has too many bugs.",
    "Two bytes meet. The first byte asks, 'Are you ill?' The second byte replies, 'No, just feeling a bit off.'",
    "What's a computer's least favorite food? Spam.",
    "Why did the developer go broke? Because he used up all his cache."
    ]

function generateRandomNumber() {
      x = Math.floor(Math.random() * 30);
      a = jokes[x];
      document.getElementById("joke").textContent = a;
}
